tag-name = "v$VERSION"
verify-command = "ruff check . && PYTHONPATH=. pytest tests/"
tarball-location = []
release-timeout = 5

[[update_version]]
path = "setuptools_gettext/__init__.py"
match = "^__version__ = ((.*))$"
new-line = "__version__ = $TUPLED_VERSION"
